name: README to PDF

on:
  push:
    paths:
      - 'README.md'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --pdf-engine=xelatex
            -V 'mainfont:Font-Regular.otf'
            -V 'mainfontoptions:BoldFont=Font-Bold.otf, ItalicFont=Font-Italic.otf, BoldItalicFont=Font-BoldItalic.otf'
            --output=README.pdf
            README.md
      - uses: actions/upload-artifact@v3
        with:
          name: README.pdf
          path: README.pdf
