name: README to PDF

on:
  push:
    paths:
      - 'README.md'

jobs:
  readme_to_pdf_html:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Convert markdown to asciidoctor
        uses: docker://pandoc/core
        with:
          args: -f markdown -t asciidoc -i README.md -o README.adoc
      - name: Convert asciidoctor to pdf
        uses: docker://asciidoctor/docker-asciidoctor
        with:
          entrypoint: asciidoctor-pdf
          args: README.adoc
      - name: Convert asciidoctor to html
        uses: docker://asciidoctor/docker-asciidoctor
        with:
          entrypoint: asciidoctor
          args: README.adoc
      - uses: actions/upload-artifact@v3
        with:
          name: README.pdf
          path: README.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: README.html
          path: README.html
