name: README to PDF

on:
  push:
    paths:
      - 'README.md'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core
        with:
          args: -f markdown -t asciidoc -i README.md -o target/README.adoc
      - uses: docker://asciidoctor/docker-asciidoctor
        with:
          args: |
            asciidoctor-pdf
            target/README.adoc
      - uses: docker://asciidoctor/docker-asciidoctor
        with:
          args: |
            asciidoctor
            target/README.adoc
      - uses: actions/upload-artifact@v3
        with:
          name: target/README.pdf
          path: target/README.html
