name: README to PDF

on:
  push:
    paths:
      - 'README.md'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core:3.1
        with:
          args: >- 
            --standalone
            --output=README.pdf
            README.md
