name: Release

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build the Docker image
        run: |
          mkdir target
          DOCKER_BUILDKIT=1 docker buildx build --output type=tar,dest=./target/docker.image.tar --platform=linux/arm64,linux/amd64 -f docker/meshmonitor-native-image.dockerfile .
          cd target
          
          # x64
          tar -xf docker.image.tar linux_amd64/meshmonitor/meshmonitor
          tar -xf docker.image.tar linux_amd64/meshmonitor/meshmonitor.1
          tar -xf docker.image.tar linux_amd64/meshmonitor/meshmonitor.html
          tar -xf docker.image.tar linux_amd64/meshmonitor/meshmonitor_completion.sh
          tar -xf docker.image.tar linux_amd64/meshmonitor/meshmonitor-1.0.0-jar-with-dependencies.jar
          
          mv linux_amd64/meshmonitor/meshmonitor-1.0.0-jar-with-dependencies.jar linux_amd64/meshmonitor/meshmonitor.jar
          tar -czf meshmonitor-linux-x64.tar.gz --directory=linux_amd64/meshmonitor meshmonitor
          
          # arm
          tar -xf docker.image.tar linux_arm64/meshmonitor/meshmonitor
          tar -czf meshmonitor-linux-arm64.tar.gz --directory=linux_arm64/meshmonitor meshmonitor
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            target/meshmonitor-linux-x64.tar.gz
            target/meshmonitor-linux-arm64.tar.gz
            target/README.pdf
            target/linux_amd64/meshmonitor/meshmonitor.1
            target/linux_amd64/meshmonitor/meshmonitor.html
            target/linux_amd64/meshmonitor/meshmonitor.jar
            target/linux_amd64/meshmonitor/meshmonitor_completion.sh
