name: Tests

on:
  push:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v3
      - name: Run tests in docker container
        run: |
          mkdir target
          DOCKER_BUILDKIT=1 docker buildx build --output type=tar,dest=./target/docker.image.tar --platform=linux/arm64,linux/amd64 -f docker/meshmonitor-native-image.tests.dockerfile .
          
          cd target
          tar -xf docker.image.tar linux_amd64/target/surefire-reports
          tar -xf docker.image.tar linux_arm64/target/surefire-reports
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/surefire-reports/TEST-*.xml'
